title: Siddique Reza Khan
logo: /assets/img/SiddiqueKhan.jpg
# Give here a description for Labguage Skill
description: '⚡ Language skills - 💡 English : Very good knowledge (Level B2 - Fluent English) and 🚀 German : Intermediate Knowledge (Level B2 - currently pursuing)'

show_downloads: false
theme: jekyll-theme-minimal
# -------- Following Part Did not Work ---------
# social-network-links:
#   email: "siddiquerezakhan@gmail.com"
#   # github: daattali
#   twitter: khaninfosec
#   # patreon: DeanAttali
#   # youtube: "@daattali"
#   linkedin: siddique-reza-khan
# share-links-active:
#   linkedin: true
# -------- END ---------

