title: Siddique Reza Khan
logo: /assets/img/SiddiqueKhan.jpg
# Give here a description for Labguage Skill
description: 'Language skills - 💡 English : Very good knowledge (B2 - Fluent English) and 🚀 German : Intermediate Knowledge (currently pursuing B1)'
show_downloads: false
theme: jekyll-theme-minimal
