title: Siddique Reza Khan
logo: /assets/img/SiddiqueKhan.jpg
description: Language skills 
- English Very good knowledge (B2 - Fluent English)
- German Intermediate Knowledge (currently pursuing B1)
show_downloads: false
theme: jekyll-theme-minimal
